In [1]:
# import required libraries
# Data Handling
import pandas as pd
import numpy as np

# Data Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Data Preprocessing
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler, LabelEncoder, OneHotEncoder
from sklearn.impute import SimpleImputer

# Feature Selection
from sklearn.feature_selection import SelectKBest, chi2, RFE

# ML Models
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB

# Evaluation
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report,
    roc_curve
)

# Imbalanced Data
from imblearn.over_sampling import SMOTE

# Warnings
import warnings
warnings.filterwarnings("ignore")

In [2]:
#! pip install imblearn

In [10]:
# load the dataset
df = pd.read_csv("Patient_Health_Records_Cleaned.csv")

In [11]:
# 1. Check dataset shape
df.shape

(4971, 19)

In [12]:
# 2. Check first rows
df.head()

,Age,Gender,City,BMI,Blood_Pressure,Heart_Rate,Cholesterol_Level,Diabetic,Smoker,Medications,Last_Visit_Date,Follow_Up,Diagnosis_Code,Notes,Has_Disease,Cholesterol_Value,Cholesterol_Status,Systolic_BP,Diastolic_BP
0,NaN,NaN,Boston,NaN,120/80,83.0,190,NaN,Yes,NaN,2021-04-15,30.0,A00,Patient feeling fine 🙂,0,190.0,NaN,120.0,80.0
1,NaN,Male,Los Angeles,30.1,120/80,NaN,normal,No,No,NaN,NaN,NaN,I10,Patient feeling fine 🙂,1,NaN,normal,120.0,80.0
2,NaN,NaN,NaN,NaN,120/80,63.0,normal,No,Former,NaN,NaN,30.0,E11.9,NaN,0,NaN,normal,120.0,80.0
3,NaN,NaN,Boston,NaN,120/80,NaN,high,No,Former,Aspirin; Metformin,NaN,30.0,NaN,NaN,0,NaN,high,120.0,80.0
4,NaN,NaN,Chicago,21.5,NaN,NaN,NaN,No,Former,NaN,NaN,30.0,A00,"BP high, needs recheck",1,NaN,NaN,NaN,NaN

In [14]:
# Convert Last_Visit_Date to datetime format
df["Last_Visit_Date"] = pd.to_datetime(
    df["Last_Visit_Date"], errors="coerce", format="mixed", dayfirst=True
)

# Extract year
df["Visit_Year"] = df["Last_Visit_Date"].dt.year

In [15]:
# drop columns which is modified as atribute constuction
df.drop(
    columns=["Blood_Pressure", "Cholesterol_Level", "Last_Visit_Date", "Diagnosis_Code", "Notes", "City"],
    inplace=True
)

In [16]:
print(df.columns.tolist())

['Age', 'Gender', 'BMI', 'Heart_Rate', 'Diabetic', 'Smoker', 'Medications', 'Follow_Up', 'Has_Disease', 'Cholesterol_Value', 'Cholesterol_Status', 'Systolic_BP', 'Diastolic_BP', 'Visit_Year']

# Independent and Dependent features split

In [17]:
# independent data split
independent = df[['Age', 'Gender', 'BMI', 'Heart_Rate', 'Diabetic', 'Smoker', 'Medications',
                  'Follow_Up', 'Cholesterol_Value', 'Cholesterol_Status',
                  'Systolic_BP', 'Diastolic_BP', 'Visit_Year']]
independent

,Age,Gender,BMI,Heart_Rate,Diabetic,Smoker,Medications,Follow_Up,Cholesterol_Value,Cholesterol_Status,Systolic_BP,Diastolic_BP,Visit_Year
0,NaN,NaN,NaN,83.0,NaN,Yes,NaN,30.0,190.0,NaN,120.0,80.0,2021.0
1,NaN,Male,30.1,NaN,No,No,NaN,NaN,NaN,normal,120.0,80.0,NaN
2,NaN,NaN,NaN,63.0,No,Former,NaN,30.0,NaN,normal,120.0,80.0,NaN
3,NaN,NaN,NaN,NaN,No,Former,Aspirin; Metformin,30.0,NaN,high,120.0,80.0,NaN
4,NaN,NaN,21.5,NaN,No,Former,NaN,30.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4966,NaN,Male,NaN,97.0,No,Yes,NaN,30.0,190.0,NaN,NaN,NaN,2022.0
4967,NaN,Male,23.6,104.0,No,NaN,Aspirin; Metformin,NaN,190.0,NaN,120.0,80.0,2020.0
4968,NaN,Female,NaN,NaN,No,Former,Aspirin; Metformin,14.0,NaN,NaN,120.0,80.0,NaN
4969,NaN,NaN,NaN,71.0,NaN,Former,Lisinopril; Metformin,NaN,190.0,NaN,120.0,80.0,NaN
4970,NaN,NaN,22.4,NaN,Yes,Former,NaN,14.0,NaN,high,112.0,98.0,NaN

In [18]:
# dpenndent data split
dependent = df[['Has_Disease']]
dependent

      Has_Disease
0               0
1               1
2               0
3               0
4               1
...           ...
4966            0
4967            0
4968            0
4969            0
4970            0

[4971 rows x 1 columns]

# Train and Test data split

In [19]:
# Train and test data split
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(independent, dependent, test_size = 0.20, random_state = 0)
X_train

,Age,Gender,BMI,Heart_Rate,Diabetic,Smoker,Medications,Follow_Up,Cholesterol_Value,Cholesterol_Status,Systolic_BP,Diastolic_BP,Visit_Year
2243,NaN,NaN,24.0,NaN,Yes,Former,NaN,14.0,NaN,normal,NaN,NaN,NaN
326,NaN,Male,18.5,NaN,Yes,Yes,Lisinopril; Metformin,14.0,NaN,high,NaN,NaN,NaN
252,NaN,Male,22.5,NaN,Yes,NaN,NaN,30.0,250.0,NaN,NaN,NaN,NaN
1248,NaN,NaN,NaN,NaN,NaN,Yes,Aspirin; Metformin,NaN,190.0,NaN,120.0,80.0,NaN
3512,NaN,Male,34.6,NaN,NaN,Former,NaN,NaN,NaN,high,NaN,NaN,2023.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4931,NaN,Female,22.5,NaN,NaN,Former,Aspirin; Metformin,NaN,NaN,high,120.0,80.0,2025.0
3264,NaN,Female,21.4,NaN,No,Yes,NaN,NaN,NaN,normal,120.0,80.0,NaN
1653,NaN,Male,NaN,NaN,No,Former,NaN,14.0,NaN,NaN,120.0,80.0,NaN
2607,NaN,Male,22.5,NaN,No,Former,Aspirin; Metformin,NaN,250.0,NaN,120.0,80.0,2022.0
2732,NaN,NaN,22.5,NaN,No,NaN,Aspirin; Metformin,14.0,190.0,NaN,120.0,80.0,NaN

In [20]:
df["Systolic_BP"].value_counts()

Systolic_BP
120.0    2960
154.0      27
143.0      22
128.0      22
92.0       21
         ...
91.0        9
136.0       9
123.0       9
158.0       9
141.0       8
Name: count, Length: 71, dtype: int64

In [21]:
df["Diastolic_BP"].value_counts()

Diastolic_BP
80.0     2974
64.0       37
94.0       33
95.0       30
60.0       29
85.0       29
63.0       29
96.0       28
72.0       28
79.0       28
92.0       28
98.0       26
97.0       26
61.0       26
83.0       25
89.0       25
81.0       25
84.0       24
74.0       24
86.0       24
62.0       24
99.0       23
75.0       23
82.0       23
93.0       23
71.0       23
68.0       22
88.0       22
100.0      22
87.0       22
65.0       22
67.0       21
78.0       21
73.0       21
66.0       21
91.0       21
70.0       19
77.0       18
90.0       17
69.0       17
76.0       16
Name: count, dtype: int64

# Filling the missing values strategy using median and mode

In [22]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer


# ---------------------------------------------
# 1. Numeric columns → Median Imputation
# ---------------------------------------------
numeric_cols = ['Age', 'BMI', 'Heart_Rate', 'Follow_Up', 
                 'Cholesterol_Value', 'Systolic_BP', 'Diastolic_BP']

num_imputer = SimpleImputer(strategy='median')

# Fit ONLY on train, transform both
X_train[numeric_cols] = num_imputer.fit_transform(X_train[numeric_cols])
X_test[numeric_cols] = num_imputer.transform(X_test[numeric_cols])

print("Medians used:", dict(zip(numeric_cols, num_imputer.statistics_)))

# ---------------------------------------------
# 2. Categorical columns → Mode Imputation
# ---------------------------------------------
categorical_cols = ['Gender', 'Diabetic', 'Smoker', 'Medications', 'Cholesterol_Status']

# Convert nullable NA to standard NaN for categorical columns
X_train[categorical_cols] = X_train[categorical_cols].astype(object).where(X_train[categorical_cols].notna(), np.nan)
X_test[categorical_cols] = X_test[categorical_cols].astype(object).where(X_test[categorical_cols].notna(), np.nan)

cat_imputer = SimpleImputer(strategy='most_frequent')
X_train[categorical_cols] = cat_imputer.fit_transform(X_train[categorical_cols])
X_test[categorical_cols] = cat_imputer.transform(X_test[categorical_cols])



# ---------------------------------------------
# 3. Visit_Year → Treat separately (date-like variable)
# ---------------------------------------------
# Option A: If Visit_Year is just a year number (e.g., 2020, 2021) → treat as numeric, use median
year_imputer = SimpleImputer(strategy='median')

X_train[['Visit_Year']] = year_imputer.fit_transform(X_train[['Visit_Year']])
X_test[['Visit_Year']] = year_imputer.transform(X_test[['Visit_Year']])

print("Visit_Year median used:", year_imputer.statistics_)

# Option B (alternative): If you prefer most common year instead of median
# year_imputer = SimpleImputer(strategy='most_frequent')

Medians used: {'Age': np.float64(50.0), 'BMI': np.float64(22.5), 'Heart_Rate': np.float64(86.0), 'Follow_Up': np.float64(14.0), 'Cholesterol_Value': np.float64(190.0), 'Systolic_BP': np.float64(120.0), 'Diastolic_BP': np.float64(80.0)}
Visit_Year median used: [2022.]

In [23]:
# Check missing values in training data
print("Missing values in X_train:")
print(X_train.isnull().sum())

print("\nTotal missing values in X_train:", X_train.isnull().sum().sum())

# Check missing values in testing data
print("\nMissing values in X_test:")
print(X_test.isnull().sum())

print("\nTotal missing values in X_test:", X_test.isnull().sum().sum())

Missing values in X_train:
Age                   0
Gender                0
BMI                   0
Heart_Rate            0
Diabetic              0
Smoker                0
Medications           0
Follow_Up             0
Cholesterol_Value     0
Cholesterol_Status    0
Systolic_BP           0
Diastolic_BP          0
Visit_Year            0
dtype: int64

Total missing values in X_train: 0

Missing values in X_test:
Age                   0
Gender                0
BMI                   0
Heart_Rate            0
Diabetic              0
Smoker                0
Medications           0
Follow_Up             0
Cholesterol_Value     0
Cholesterol_Status    0
Systolic_BP           0
Diastolic_BP          0
Visit_Year            0
dtype: int64

Total missing values in X_test: 0

In [24]:
import pickle

# Save numeric imputer
pickle.dump(num_imputer, open("num_imputer.pkl", "wb"))

# Save categorical imputer
pickle.dump(cat_imputer, open("cat_imputer.pkl", "wb"))

# Save Visit_Year imputer
pickle.dump(year_imputer, open("year_imputer.pkl", "wb"))

In [29]:
# below code for capping outliers but blood pressure needs high and low for anlysing and model building so i dont apply any capping method

In [30]:
#import numpy as np
#from sklearn.preprocessing import QuantileTransformer, PowerTransformer

#cols = ["Age", "BMI", "Heart_Rate", "Systolic_BP", "Diastolic_BP"]

# cast nullable Int64 / <NA> to plain float (impute NaNs before this if your model needs it)
#X_train[cols] = X_train[cols].astype(float)
#X_test[cols]  = X_test[cols].astype(float)

# Option A (best for your data): forces a normal shape
#qt = QuantileTransformer(output_distribution="normal", n_quantiles=1000, random_state=42)
#X_train[cols] = qt.fit_transform(X_train[cols])   # fit on train only
#X_test[cols]  = qt.transform(X_test[cols])        # reuse the same fit

# Option B: gentler power transform (Yeo-Johnson)
#pt = PowerTransformer(method="yeo-johnson", standardize=True)
#X_train[cols] = pt.fit_transform(X_train[cols])
#X_test[cols]  = pt.transform(X_test[cols])

In [31]:
#X_train[cols] = X_train[cols].clip(-3, 3)
#X_test[cols]  = X_test[cols].clip(-3, 3)

In [32]:
#import matplotlib.pyplot as plt
#from scipy import stats

#cols = ["Age", "BMI", "Heart_Rate", "Systolic_BP", "Diastolic_BP"]

#fig, axes = plt.subplots(2, 3, figsize=(15, 8))
#axes = axes.ravel()

#for ax, col in zip(axes, cols):
    #stats.probplot(X_train[col].dropna().astype(float), dist="norm", plot=ax)
    #ax.set_title(f"QQ Plot - {col} (after transformation)")

# hide the unused 6th subplot
#for ax in axes[len(cols):]:
    #ax.set_visible(False)

#plt.tight_layout()
#plt.show()

In [33]:
# the data set has more than 60% of datas are missing and nan value when you apply for mean median and mode for filling
# the missing values those most of the datas will be stayed in center place and the datas are in plausible range so i dont 
# apply any transformation techniques

In [34]:
#from sklearn.preprocessing import MinMaxScaler

#cols = ["Age", "BMI", "Heart_Rate", "Systolic_BP", "Diastolic_BP"]

# after QuantileTransformer + clip(-3, 3)

#scaler = MinMaxScaler()                      # range 0 to 1
#X_train[cols] = scaler.fit_transform(X_train[cols])   # fit on train only
#X_test[cols]  = scaler.transform(X_test[cols])        # reuse the same fit

#from sklearn.preprocessing import PowerTransformer

# Power Transformation (Yeo-Johnson method)
#power = PowerTransformer(method="yeo-johnson", standardize=True)

# Fit on training data only
#X_train[cols] = power.fit_transform(X_train[cols])

# Apply the same transformation to test data
#X_test[cols] = power.transform(X_test[cols])

# Feature engineering 
## Atribute construction

# Medication count

In [35]:
# Count the number of medications
def add_medication_count(df):
    df = df.copy()

    df["Medication_Count"] = (
        df["Medications"]
        .fillna("")
        .str.split(";")
        .apply(lambda x: len([med for med in x if med.strip() != ""]))
    )

    return df


# Apply separately
X_train = add_medication_count(X_train)
X_test = add_medication_count(X_test)

# Age_group

In [36]:
def add_age_group(df):
    df = df.copy()

    df["Age_Group"] = pd.cut(
        df["Age"],
        bins=[0, 18, 40, 60, 100],
        labels=["Young", "Adult", "Middle_Age", "Senior"]
    )

    return df


X_train = add_age_group(X_train)
X_test = add_age_group(X_test)

# BMI category

In [37]:
def add_bmi_category(df):
    df = df.copy()

    df["BMI_Category"] = pd.cut(
        df["BMI"],
        bins=[0, 18.5, 25, 30, 100],
        labels=["Underweight", "Normal", "Overweight", "Obese"]
    )

    return df


X_train = add_bmi_category(X_train)
X_test = add_bmi_category(X_test)

# BP category

In [38]:
def add_bp_category(df):
    df = df.copy()

    sys = pd.to_numeric(df["Systolic_BP"], errors="coerce").to_numpy(dtype=float)
    dia = pd.to_numeric(df["Diastolic_BP"], errors="coerce").to_numpy(dtype=float)

    df["BP_Category"] = np.select(
        [
            (sys < 120) & (dia < 80),
            (sys < 130) & (dia < 80),
            (sys >= 130) | (dia >= 80),
        ],
        ["Normal", "Elevated", "Hypertensive"],
        default="Unknown",
    )
    return df

# Risk score

In [39]:
def add_risk_score(df):
    df = df.copy()

    # Safe conversions (handles Int64 / <NA> / NaN)
    age = pd.to_numeric(df["Age"], errors="coerce").astype(float)
    bmi = pd.to_numeric(df["BMI"], errors="coerce").astype(float)
    sys = pd.to_numeric(df["Systolic_BP"], errors="coerce").astype(float)
    dia = pd.to_numeric(df["Diastolic_BP"], errors="coerce").astype(float)
    hr  = pd.to_numeric(df["Heart_Rate"], errors="coerce").astype(float)

    chol     = df["Cholesterol_Status"].astype("string").str.lower()
    smoker   = df["Smoker"].astype("string").str.lower()
    diabetic = df["Diabetic"].astype("string").str.lower()

    def pts(cond, p):
        # missing comparison -> False -> 0 points
        return cond.fillna(False).astype(int) * p

    score = (
        pts(age >= 60, 2) + pts((age >= 45) & (age < 60), 1)
        + pts(bmi >= 30, 2) + pts((bmi >= 25) & (bmi < 30), 1)
        + pts((sys >= 130) | (dia >= 85), 2)
        + pts(hr > 100, 1)
        + pts(chol == "high", 2)
        + pts(diabetic == "yes", 2)
        + pts(smoker == "yes", 2) + pts(smoker == "former", 1)
    )

    df["Risk_Points"] = score
    df["Risk_Score"] = pd.cut(
        score, bins=[-1, 2, 5, 100], labels=["Low", "Medium", "High"]
    ).astype(str)

    return df

X_train = add_risk_score(X_train)
X_test = add_risk_score(X_test)

print(X_train["Risk_Score"].value_counts())

Risk_Score
Medium    2153
Low       1319
High       504
Name: count, dtype: int64

In [40]:
# Check the column names in X_train
print(X_train.columns)

Index(['Age', 'Gender', 'BMI', 'Heart_Rate', 'Diabetic', 'Smoker',
       'Medications', 'Follow_Up', 'Cholesterol_Value', 'Cholesterol_Status',
       'Systolic_BP', 'Diastolic_BP', 'Visit_Year', 'Medication_Count',
       'Age_Group', 'BMI_Category', 'Risk_Points', 'Risk_Score'],
      dtype='object')

In [41]:
# Check the column names in X_train
print(X_test.columns)

Index(['Age', 'Gender', 'BMI', 'Heart_Rate', 'Diabetic', 'Smoker',
       'Medications', 'Follow_Up', 'Cholesterol_Value', 'Cholesterol_Status',
       'Systolic_BP', 'Diastolic_BP', 'Visit_Year', 'Medication_Count',
       'Age_Group', 'BMI_Category', 'Risk_Points', 'Risk_Score'],
      dtype='object')

In [42]:
new_cols = [
    "Medication_Count",
    "Age_Group",
    "BMI_Category",
    "Risk_Score"
]

print(X_train[new_cols].head())

      Medication_Count   Age_Group BMI_Category Risk_Score
2243                 2  Middle_Age       Normal     Medium
326                  2  Middle_Age  Underweight       High
252                  2  Middle_Age       Normal     Medium
1248                 2  Middle_Age       Normal     Medium
3512                 2  Middle_Age        Obese       High

In [43]:
print("X_train:")
print(X_train[new_cols].head())

X_train:
      Medication_Count   Age_Group BMI_Category Risk_Score
2243                 2  Middle_Age       Normal     Medium
326                  2  Middle_Age  Underweight       High
252                  2  Middle_Age       Normal     Medium
1248                 2  Middle_Age       Normal     Medium
3512                 2  Middle_Age        Obese       High

In [44]:
print("\nX_test:")
print(X_test[new_cols].head())

X_test:
      Medication_Count   Age_Group BMI_Category Risk_Score
3129                 2  Middle_Age        Obese       High
2108                 2       Young       Normal     Medium
2781                 2  Middle_Age       Normal        Low
1091                 2  Middle_Age       Normal     Medium
3975                 2  Middle_Age       Normal        Low

# Identify categorical and numerical columns

In [45]:
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder

onehot_cols = [
    "Gender",
    "Diabetic",
    "Smoker",
    "Medications",
    "Cholesterol_Status"
]

ordinal_cols = [
    "Age_Group",
    "BMI_Category",
    "Risk_Score"
]

numerical_cols = [
    "Age",
    "BMI",
    "Heart_Rate",
    "Follow_Up",
    "Cholesterol_Value",
    "Systolic_BP",
    "Diastolic_BP",
    "Visit_Year",
    "Medication_Count"
]

# Create and fit the encoder

In [47]:
# 2. One-Hot Encoding (drop first category)

encoder = OneHotEncoder(
    handle_unknown="ignore",
    drop="first",
    sparse_output=False
)

X_train_cat = encoder.fit_transform(X_train[onehot_cols])
X_test_cat = encoder.transform(X_test[onehot_cols])

# Get One-Hot feature names
onehot_feature_names = encoder.get_feature_names_out(onehot_cols)

X_train_cat = pd.DataFrame(
    X_train_cat,
    columns=onehot_feature_names,
    index=X_train.index
)

X_test_cat = pd.DataFrame(
    X_test_cat,
    columns=onehot_feature_names,
    index=X_test.index
)

In [48]:
# 3. Ordinal Encoding

ordinal_encoder = OrdinalEncoder(
    categories=[
        ["Young", "Adult", "Middle_Age", "Senior"],
        ["Underweight", "Normal", "Overweight", "Obese"],
        ["Low", "Medium", "High"]
    ],
    handle_unknown="use_encoded_value",
    unknown_value=-1
)

X_train_ord = ordinal_encoder.fit_transform(X_train[ordinal_cols])
X_test_ord = ordinal_encoder.transform(X_test[ordinal_cols])

X_train_ord = pd.DataFrame(
    X_train_ord,
    columns=ordinal_cols,
    index=X_train.index
)

X_test_ord = pd.DataFrame(
    X_test_ord,
    columns=ordinal_cols,
    index=X_test.index
)

# Keep numerical columns

In [49]:
# 4. Keep numerical columns and combine all encoded columns

X_train_num = X_train[numerical_cols].copy()
X_test_num = X_test[numerical_cols].copy()

# Combine numerical + encoded categorical columns

In [50]:
X_train_encoded = pd.concat(
    [X_train_num, X_train_cat, X_train_ord],
    axis=1
)

X_test_encoded = pd.concat(
    [X_test_num, X_test_cat, X_test_ord],
    axis=1
)

# Save the encoder

In [51]:
# 5. Save both encoders

with open("onehot_encoder.pkl", "wb") as file:
    pickle.dump(encoder, file)

with open("ordinal_encoder.pkl", "wb") as file:
    pickle.dump(ordinal_encoder, file)

In [52]:
# 6. Check the final encoded data

print("Training data shape:", X_train_encoded.shape)
print("Testing data shape:", X_test_encoded.shape)

Training data shape: (3976, 18)
Testing data shape: (995, 18)

In [53]:
print("\nEncoded training columns:")
print(X_train_encoded.columns.tolist())

Encoded training columns:
['Age', 'BMI', 'Heart_Rate', 'Follow_Up', 'Cholesterol_Value', 'Systolic_BP', 'Diastolic_BP', 'Visit_Year', 'Medication_Count', 'Gender_Male', 'Diabetic_Yes', 'Smoker_No', 'Smoker_Yes', 'Medications_Lisinopril; Metformin', 'Cholesterol_Status_normal', 'Age_Group', 'BMI_Category', 'Risk_Score']

In [54]:
print("\nFirst 5 rows of training data:")
print(X_train_encoded.head())

First 5 rows of training data:
       Age   BMI  Heart_Rate  Follow_Up  Cholesterol_Value  Systolic_BP  \
2243  50.0  24.0        86.0       14.0              190.0        120.0
326   50.0  18.5        86.0       14.0              190.0        120.0
252   50.0  22.5        86.0       30.0              250.0        120.0
1248  50.0  22.5        86.0       14.0              190.0        120.0
3512  50.0  34.6        86.0       14.0              190.0        120.0

      Diastolic_BP  Visit_Year  Medication_Count  Gender_Male  Diabetic_Yes  \
2243          80.0      2022.0                 2          0.0           1.0
326           80.0      2022.0                 2          1.0           1.0
252           80.0      2022.0                 2          1.0           1.0
1248          80.0      2022.0                 2          0.0           0.0
3512          80.0      2023.0                 2          1.0           0.0

      Smoker_No  Smoker_Yes  Medications_Lisinopril; Metformin  \
2243        0.0         0.0                                0.0
326         0.0         1.0                                1.0
252         0.0         0.0                                0.0
1248        0.0         1.0                                0.0
3512        0.0         0.0                                0.0

      Cholesterol_Status_normal  Age_Group  BMI_Category  Risk_Score
2243                        1.0        2.0           1.0         1.0
326                         0.0        2.0           0.0         2.0
252                         1.0        2.0           1.0         1.0
1248                        1.0        2.0           1.0         1.0
3512                        0.0        2.0           3.0         2.0

In [55]:
print("\nFirst 5 rows of testing data:")
print(X_test_encoded.head())

First 5 rows of testing data:
       Age   BMI  Heart_Rate  Follow_Up  Cholesterol_Value  Systolic_BP  \
3129  50.0  34.6       120.0       30.0              190.0         97.0
2108   1.0  22.5        86.0       30.0              190.0        120.0
2781  50.0  22.5        86.0       14.0              190.0        120.0
1091  50.0  22.5        86.0       14.0              190.0        120.0
3975  50.0  24.7        96.0       14.0              190.0        120.0

      Diastolic_BP  Visit_Year  Medication_Count  Gender_Male  Diabetic_Yes  \
3129          95.0      2023.0                 2          0.0           0.0
2108          80.0      2022.0                 2          0.0           0.0
2781          80.0      2022.0                 2          1.0           0.0
1091          80.0      2022.0                 2          1.0           1.0
3975          80.0      2022.0                 2          1.0           0.0

      Smoker_No  Smoker_Yes  Medications_Lisinopril; Metformin  \
3129        0.0         0.0                                1.0
2108        0.0         0.0                                0.0
2781        0.0         0.0                                0.0
1091        0.0         0.0                                0.0
3975        0.0         0.0                                0.0

      Cholesterol_Status_normal  Age_Group  BMI_Category  Risk_Score
3129                        1.0        2.0           3.0         2.0
2108                        0.0        0.0           1.0         1.0
2781                        1.0        2.0           1.0         0.0
1091                        1.0        2.0           1.0         1.0
3975                        1.0        2.0           1.0         0.0

In [56]:
# Check missing values in training data
print("Missing values in X_train_encoded:")
print(X_train_encoded.isna().sum())

Missing values in X_train_encoded:
Age                                  0
BMI                                  0
Heart_Rate                           0
Follow_Up                            0
Cholesterol_Value                    0
Systolic_BP                          0
Diastolic_BP                         0
Visit_Year                           0
Medication_Count                     0
Gender_Male                          0
Diabetic_Yes                         0
Smoker_No                            0
Smoker_Yes                           0
Medications_Lisinopril; Metformin    0
Cholesterol_Status_normal            0
Age_Group                            0
BMI_Category                         0
Risk_Score                           0
dtype: int64

In [57]:
print("\nTotal missing values in training data:")
print(X_train_encoded.isna().sum().sum())

Total missing values in training data:
0

In [58]:
# Check missing values in testing data
print("\nMissing values in X_test_encoded:")
print(X_test_encoded.isna().sum())

Missing values in X_test_encoded:
Age                                  0
BMI                                  0
Heart_Rate                           0
Follow_Up                            0
Cholesterol_Value                    0
Systolic_BP                          0
Diastolic_BP                         0
Visit_Year                           0
Medication_Count                     0
Gender_Male                          0
Diabetic_Yes                         0
Smoker_No                            0
Smoker_Yes                           0
Medications_Lisinopril; Metformin    0
Cholesterol_Status_normal            0
Age_Group                            0
BMI_Category                         0
Risk_Score                           0
dtype: int64

In [59]:
print("\nTotal missing values in testing data:")
print(X_test_encoded.isna().sum().sum())

Total missing values in testing data:
0

In [60]:
# Display rows containing NaN values in training data
print(X_train_encoded[X_train_encoded.isna().any(axis=1)])

# Display rows containing NaN values in testing data
print(X_test_encoded[X_test_encoded.isna().any(axis=1)])

Empty DataFrame
Columns: [Age, BMI, Heart_Rate, Follow_Up, Cholesterol_Value, Systolic_BP, Diastolic_BP, Visit_Year, Medication_Count, Gender_Male, Diabetic_Yes, Smoker_No, Smoker_Yes, Medications_Lisinopril; Metformin, Cholesterol_Status_normal, Age_Group, BMI_Category, Risk_Score]
Index: []
Empty DataFrame
Columns: [Age, BMI, Heart_Rate, Follow_Up, Cholesterol_Value, Systolic_BP, Diastolic_BP, Visit_Year, Medication_Count, Gender_Male, Diabetic_Yes, Smoker_No, Smoker_Yes, Medications_Lisinopril; Metformin, Cholesterol_Status_normal, Age_Group, BMI_Category, Risk_Score]
Index: []

In [61]:
# 1. Check missing values in encoded training data
print("Training NaN values:", X_train_encoded.isna().sum().sum())

Training NaN values: 0

In [62]:
# 2. Check missing values in encoded testing data
print("Testing NaN values:", X_test_encoded.isna().sum().sum())

Testing NaN values: 0

In [63]:
# 3. Check for infinity values
print("Training infinity values:",
      np.isinf(X_train_encoded.select_dtypes(include="number")).sum().sum())

Training infinity values: 0

# Feature selection
# selectkbest

In [64]:
# ============================================================
# 1. IMPORT LIBRARIES
# ============================================================

import pandas as pd
from sklearn.feature_selection import SelectKBest, f_classif, RFE
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [65]:
# ============================================================
# 2. SELECTKBEST FEATURE SELECTION
# ============================================================

def selectkbest(X_train, X_test, Y_train, k):

    # Select features using the training data
    selector = SelectKBest(score_func=f_classif, k=k)

    X_train_selected = selector.fit_transform(X_train, Y_train)

    # Apply the same selected features to testing data
    X_test_selected = selector.transform(X_test)

    # Get selected feature names
    selected_features = X_train.columns[selector.get_support()]

    # Convert arrays into DataFrames
    X_train_selected = pd.DataFrame(
        X_train_selected,
        columns=selected_features,
        index=X_train.index
    )

    X_test_selected = pd.DataFrame(
        X_test_selected,
        columns=selected_features,
        index=X_test.index
    )

    print("Selected Features:")
    print(selected_features.tolist())

    print("Training shape:", X_train_selected.shape)
    print("Testing shape:", X_test_selected.shape)

    return X_train_selected, X_test_selected, selector

In [66]:
# ============================================================
# 3. SELECT THE BEST 6 FEATURES
# ============================================================

X_train_selected, X_test_selected, selector = selectkbest(
    X_train_encoded,
    X_test_encoded,
    Y_train,
    6
)

Selected Features:
['Age', 'Heart_Rate', 'Follow_Up', 'Cholesterol_Status_normal', 'Age_Group', 'BMI_Category']
Training shape: (3976, 6)
Testing shape: (995, 6)

In [67]:
# ============================================================
# 4. FEATURE SCALING
# ============================================================

scaler = StandardScaler()

# Fit scaler on training data only
X_train_scaled = scaler.fit_transform(X_train_selected)

# Apply the same scaler to testing data
X_test_scaled = scaler.transform(X_test_selected)

In [68]:
# ============================================================
# 5. CONFUSION MATRIX, ACCURACY AND CLASSIFICATION REPORT
# ============================================================

def cm_prediction(classifier, X_test, Y_test):

    Y_pred = classifier.predict(X_test)

    cm = confusion_matrix(Y_test, Y_pred)
    Accuracy = accuracy_score(Y_test, Y_pred)
    report = classification_report(Y_test, Y_pred, zero_division=0)

    return classifier, Accuracy, report, cm

In [69]:
# ============================================================
# 6. DEFINE CLASSIFICATION MODELS
# ============================================================

def logistic(X_train, Y_train, X_test, Y_test):

    classifier = LogisticRegression(
        max_iter=1000,
        random_state=0
    )

    classifier.fit(X_train, Y_train)

    return cm_prediction(classifier, X_test, Y_test)


def svm_linear(X_train, Y_train, X_test, Y_test):

    classifier = SVC(
        kernel="linear",
        random_state=0
    )

    classifier.fit(X_train, Y_train)

    return cm_prediction(classifier, X_test, Y_test)


def svm_NL(X_train, Y_train, X_test, Y_test):

    classifier = SVC(
        kernel="rbf",
        random_state=0
    )

    classifier.fit(X_train, Y_train)

    return cm_prediction(classifier, X_test, Y_test)


def naive(X_train, Y_train, X_test, Y_test):

    classifier = GaussianNB()

    classifier.fit(X_train, Y_train)

    return cm_prediction(classifier, X_test, Y_test)


def knn(X_train, Y_train, X_test, Y_test):

    classifier = KNeighborsClassifier(
        n_neighbors=6,
        metric="minkowski",
        p=2
    )

    classifier.fit(X_train, Y_train)

    return cm_prediction(classifier, X_test, Y_test)


def Decision(X_train, Y_train, X_test, Y_test):

    classifier = DecisionTreeClassifier(
        criterion="entropy",
        random_state=0
    )

    classifier.fit(X_train, Y_train)

    return cm_prediction(classifier, X_test, Y_test)


def random(X_train, Y_train, X_test, Y_test):

    classifier = RandomForestClassifier(
        n_estimators=10,
        criterion="entropy",
        random_state=0
    )

    classifier.fit(X_train, Y_train)

    return cm_prediction(classifier, X_test, Y_test)

In [70]:
# ============================================================
# 7. TRAIN AND EVALUATE ALL MODELS - SELECTKBEST
# ============================================================

models = {
    "Logistic": logistic,
    "SVM Linear": svm_linear,
    "SVM RBF": svm_NL,
    "KNN": knn,
    "Naive Bayes": naive,
    "Decision Tree": Decision,
    "Random Forest": random
}

selectkbest_results = {}

for name, model_function in models.items():

    classifier, Accuracy, report, cm = model_function(
        X_train_scaled,
        Y_train,
        X_test_scaled,
        Y_test
    )

    selectkbest_results[name] = Accuracy

    print("\nModel:", name)
    print("Accuracy:", Accuracy)
    print("Confusion Matrix:\n", cm)
    print("Classification Report:\n", report)

Model: Logistic
Accuracy: 0.4824120603015075
Confusion Matrix:
 [[296 188]
 [327 184]]
Classification Report:
               precision    recall  f1-score   support

           0       0.48      0.61      0.53       484
           1       0.49      0.36      0.42       511

    accuracy                           0.48       995
   macro avg       0.48      0.49      0.48       995
weighted avg       0.49      0.48      0.47       995


Model: SVM Linear
Accuracy: 0.46934673366834173
Confusion Matrix:
 [[381 103]
 [425  86]]
Classification Report:
               precision    recall  f1-score   support

           0       0.47      0.79      0.59       484
           1       0.46      0.17      0.25       511

    accuracy                           0.47       995
   macro avg       0.46      0.48      0.42       995
weighted avg       0.46      0.47      0.41       995


Model: SVM RBF
Accuracy: 0.4743718592964824
Confusion Matrix:
 [[351 133]
 [390 121]]
Classification Report:
               precision    recall  f1-score   support

           0       0.47      0.73      0.57       484
           1       0.48      0.24      0.32       511

    accuracy                           0.47       995
   macro avg       0.48      0.48      0.44       995
weighted avg       0.48      0.47      0.44       995


Model: KNN
Accuracy: 0.5316582914572864
Confusion Matrix:
 [[212 272]
 [194 317]]
Classification Report:
               precision    recall  f1-score   support

           0       0.52      0.44      0.48       484
           1       0.54      0.62      0.58       511

    accuracy                           0.53       995
   macro avg       0.53      0.53      0.53       995
weighted avg       0.53      0.53      0.53       995


Model: Naive Bayes
Accuracy: 0.48542713567839196
Confusion Matrix:
 [[281 203]
 [309 202]]
Classification Report:
               precision    recall  f1-score   support

           0       0.48      0.58      0.52       484
           1       0.50      0.40      0.44       511

    accuracy                           0.49       995
   macro avg       0.49      0.49      0.48       995
weighted avg       0.49      0.49      0.48       995


Model: Decision Tree
Accuracy: 0.5005025125628141
Confusion Matrix:
 [[373 111]
 [386 125]]
Classification Report:
               precision    recall  f1-score   support

           0       0.49      0.77      0.60       484
           1       0.53      0.24      0.33       511

    accuracy                           0.50       995
   macro avg       0.51      0.51      0.47       995
weighted avg       0.51      0.50      0.46       995


Model: Random Forest
Accuracy: 0.4934673366834171
Confusion Matrix:
 [[316 168]
 [336 175]]
Classification Report:
               precision    recall  f1-score   support

           0       0.48      0.65      0.56       484
           1       0.51      0.34      0.41       511

    accuracy                           0.49       995
   macro avg       0.50      0.50      0.48       995
weighted avg       0.50      0.49      0.48       995

In [71]:
# ============================================================
# 8. COMPARE SELECTKBEST MODEL ACCURACIES
# ============================================================

result_selectkbest = pd.DataFrame(
    {"SelectKBest": selectkbest_results}
)

print("\nSelectKBest Model Accuracy Comparison:")
print(result_selectkbest)

SelectKBest Model Accuracy Comparison:
               SelectKBest
Logistic          0.482412
SVM Linear        0.469347
SVM RBF           0.474372
KNN               0.531658
Naive Bayes       0.485427
Decision Tree     0.500503
Random Forest     0.493467

In [72]:
# ============================================================
# 9. CHECK CLASS COUNTS
# ============================================================

print("\nTraining Class Counts:")
print(Y_train.value_counts())

print("\nTraining Class Percentages:")
print(Y_train.value_counts(normalize=True) * 100)

Training Class Counts:
Has_Disease
0              2028
1              1948
Name: count, dtype: int64

Training Class Percentages:
Has_Disease
0              51.006036
1              48.993964
Name: proportion, dtype: float64

# RFE

In [73]:
# 2. Feature Scaling before RFE
#scaler_rfe = StandardScaler()

#X_train_all_scaled = scaler_rfe.fit_transform(X_train_encoded)
#X_test_all_scaled = scaler_rfe.transform(X_test_encoded)

In [74]:
# 3. RFE Feature Selection
#def rfe_selection(X_train, Y_train, X_test, n):

    #estimator = LogisticRegression(
        #max_iter=1000,
        #random_state=0
    #)

    #selector = RFE(
        #estimator=estimator,
        #n_features_to_select=n
    #)

    # Fit RFE using training data only
    #X_train_selected = selector.fit_transform(X_train, Y_train)

    # Apply the same selection to test data
    #X_test_selected = selector.transform(X_test)

    # Get selected feature names
    #selected_features = X_train.columns[selector.get_support()]

    # Convert selected arrays into DataFrames
    #X_train_selected = pd.DataFrame(
        #X_train_selected,
        #columns=selected_features,
        #index=X_train.index
    #)

    #X_test_selected = pd.DataFrame(
        #X_test_selected,
        #columns=selected_features,
        #index=X_test.index
    #)

    #print("Selected Features:")
    #print(selected_features.tolist())

    #print("Training shape:", X_train_selected.shape)
    #print("Testing shape:", X_test_selected.shape)

    #return X_train_selected, X_test_selected, selector

In [75]:
# 4. Select 6 features
#X_train_rfe, X_test_rfe, rfe = rfe_selection(
    #X_train_encoded,
    #Y_train,
    #X_test_encoded,
    #6
#)

# Convert selected scaled arrays to DataFrames
# using the selected feature names
#X_train_rfe_scaled = pd.DataFrame(
    #X_train_rfe,
    #columns=X_train_rfe.columns,
    #index=X_train_rfe.index
#)

#X_test_rfe_scaled = pd.DataFrame(
    #X_test_rfe,
    #columns=X_test_rfe.columns,
    #index=X_test_rfe.index
#)

In [76]:
# 5. Confusion Matrix, Accuracy and Classification Report
#def cm_prediction(classifier, X_test, Y_test):

    #Y_pred = classifier.predict(X_test)

    #cm = confusion_matrix(Y_test, Y_pred)
    #Accuracy = accuracy_score(Y_test, Y_pred)
    #report = classification_report(Y_test, Y_pred, zero_division=0)

    #return classifier, Accuracy, report, cm

In [77]:
# 6. Define classification models
#models_rfe = {
    #"Logistic": LogisticRegression(max_iter=1000, random_state=0),
    #"SVM Linear": SVC(kernel="linear", random_state=0),
    #"SVM RBF": SVC(kernel="rbf", random_state=0),
    #"KNN": KNeighborsClassifier(
        #n_neighbors=5, metric="minkowski", p=2
    #),
    #"Naive Bayes": GaussianNB(),
    #"Decision Tree": DecisionTreeClassifier(
        #criterion="entropy", random_state=0
    #),
    #"Random Forest": RandomForestClassifier(
        #n_estimators=10, criterion="entropy", random_state=0
    #)
#}

In [78]:
# 7. Train and evaluate all models
#results_rfe = []
#trained_models_rfe = {}

#for name, classifier in models_rfe.items():

    #classifier.fit(X_train_rfe_scaled, Y_train)

    #classifier, Accuracy, report, cm = cm_prediction(
        #classifier, X_test_rfe_scaled, Y_test
    #)

    #results_rfe.append({
        #"Model": name,
        #"Accuracy": Accuracy
    #})

    #trained_models_rfe[name] = classifier

    #print("\n", name)
    #print("Accuracy:", Accuracy)
    #print("Classification Report:\n", report)
    #print("Confusion Matrix:\n", cm)

In [79]:
# 8. Compare model accuracy
#result_rfe = pd.DataFrame(results_rfe)
#result_rfe = result_rfe.set_index("Model")

#print("\nRFE Model Accuracy Comparison:")
#print(result_rfe)

In [80]:
# 9. Check class counts and percentages
#print("\nTraining Class Counts:")
#print(Y_train.value_counts())

#print("\nTraining Class Percentages:")
#print(Y_train.value_counts(normalize=True) * 100)

In [81]:

# 10. Display selected features and shapes
#print("\nSelected RFE Features:")
#print(X_train_rfe.columns.tolist())

#print("Training shape:", X_train_rfe.shape)
#print("Testing shape:", X_test_rfe.shape)

In [82]:
#X_train_rfe_scaled = X_train_rfe
#X_test_rfe_scaled = X_test_rfe

In [83]:
import pickle

# Save the fitted SelectKBest feature selector
with open("SelectKBest_selector.pkl", "wb") as file:
    pickle.dump(selector, file)

In [84]:
# Check correlation with target
print(df[numeric_cols + ["Has_Disease"]].corr()["Has_Disease"].sort_values())

Age                 -0.037896
Cholesterol_Value    0.006940
Systolic_BP          0.009517
Follow_Up            0.014827
Diastolic_BP         0.015071
BMI                  0.016892
Heart_Rate           0.038645
Has_Disease          1.000000
Name: Has_Disease, dtype: float64

In [85]:
from sklearn.feature_selection import mutual_info_classif
X_enc = X_train_cat  # your one-hot encoded categoricals
mi = mutual_info_classif(X_enc, Y_train, discrete_features=True)
print(pd.Series(mi, index=encoder.get_feature_names_out()).sort_values(ascending=False).head(10))

Cholesterol_Status_normal            0.000332
Medications_Lisinopril; Metformin    0.000073
Diabetic_Yes                         0.000064
Gender_Male                          0.000062
Smoker_No                            0.000053
Smoker_Yes                           0.000002
dtype: float64

In [86]:
print(pd.crosstab(df["Gender"], df["Has_Disease"], normalize="index"))

print(pd.crosstab(df["Diabetic"], df["Has_Disease"], normalize="index"))

print(pd.crosstab(df["Smoker"], df["Has_Disease"], normalize="index"))

Has_Disease         0         1
Gender
Female       0.502413  0.497587
Male         0.514742  0.485258
Has_Disease         0         1
Diabetic
No           0.496491  0.503509
Yes          0.498139  0.501861
Has_Disease         0         1
Smoker
Former       0.505263  0.494737
No           0.495818  0.504182
Yes          0.510278  0.489722

In [87]:
from sklearn.preprocessing import StandardScaler

# Create StandardScaler
scaler_kbest = StandardScaler()

# Fit scaler only on selected training features
X_train_scaled = scaler_kbest.fit_transform(X_train_selected)

# Apply the same scaler to selected test features
X_test_scaled = scaler_kbest.transform(X_test_selected)

print("Scaled X_train:")
print(X_train_scaled[:5])

print("\nScaled X_test:")
print(X_test_scaled[:5])

Scaled X_train:
[[ 0.01197202  0.01883601 -0.56147106  0.4778052   0.09460007 -0.22176729]
 [ 0.01197202  0.01883601 -0.56147106 -2.09290314  0.09460007 -2.0249304 ]
 [ 0.01197202  0.01883601  1.78103569  0.4778052   0.09460007 -0.22176729]
 [ 0.01197202  0.01883601 -0.56147106  0.4778052   0.09460007 -0.22176729]
 [ 0.01197202  0.01883601 -0.56147106 -2.09290314  0.09460007  3.38455892]]

Scaled X_test:
[[ 0.01197202  3.30441996  1.78103569  0.4778052   0.09460007  3.38455892]
 [-3.27314916  0.01883601  1.78103569 -2.09290314 -3.19037701 -0.22176729]
 [ 0.01197202  0.01883601 -0.56147106  0.4778052   0.09460007 -0.22176729]
 [ 0.01197202  0.01883601 -0.56147106  0.4778052   0.09460007 -0.22176729]
 [ 0.01197202  0.98518423 -0.56147106  0.4778052   0.09460007 -0.22176729]]

In [88]:
# Save the fitted StandardScaler
with open("SelectKBest_scaler.pkl", "wb") as file:
    pickle.dump(scaler_kbest, file)

print("SelectKBest feature selector and StandardScaler saved successfully.")

SelectKBest feature selector and StandardScaler saved successfully.

# Model building
# KNN classification

In [242]:
# 1. Import libraries
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import (
    confusion_matrix,
    classification_report,
    f1_score,
    roc_auc_score
)

In [243]:
# 2. Hyperparameter tuning
param_grid = {
    "n_neighbors": [3, 5, 7, 9],
    "weights": ["uniform", "distance"],
    "metric": ["euclidean", "manhattan", "minkowski"],
    "p": [1, 2]
}

grid = GridSearchCV(
    estimator=KNeighborsClassifier(),
    param_grid=param_grid,
    refit=True,
    verbose=3,
    n_jobs=-1,
    scoring="f1_weighted"
)

In [244]:
# 3. Train using SelectKBest-selected and scaled features
grid.fit(X_train_scaled, Y_train)

Fitting 5 folds for each of 48 candidates, totalling 240 fits

GridSearchCV(estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'metric': ['euclidean', 'manhattan', 'minkowski'],
                         'n_neighbors': [3, 5, 7, 9], 'p': [1, 2],
                         'weights': ['uniform', 'distance']},
             scoring='f1_weighted', verbose=3)

In [245]:
# 4. Get GridSearchCV results
re = grid.cv_results_

# Predict using the selected and scaled test features
grid_predictions = grid.predict(X_test_scaled)

# Model evaluation

In [246]:
# 5. Confusion matrix and best parameters
cm = confusion_matrix(Y_test, grid_predictions)

print("Best Parameters:", grid.best_params_)
print("Best Cross-Validation Score:", grid.best_score_)
print("Confusion Matrix:\n", cm)

Best Parameters: {'metric': 'manhattan', 'n_neighbors': 9, 'p': 1, 'weights': 'uniform'}
Best Cross-Validation Score: 0.5004887518667688
Confusion Matrix:
 [[146 338]
 [138 373]]

In [247]:
# 6. Classification report
clf_report = classification_report(
    Y_test,
    grid_predictions,
    zero_division=0
)

print("Classification Report:\n", clf_report)

Classification Report:
               precision    recall  f1-score   support

           0       0.51      0.30      0.38       484
           1       0.52      0.73      0.61       511

    accuracy                           0.52       995
   macro avg       0.52      0.52      0.50       995
weighted avg       0.52      0.52      0.50       995

In [248]:
# 7. Weighted F1 score
f1_weighted = f1_score(
    Y_test,
    grid_predictions,
    average="weighted"
)

print("Weighted F1 Score:", f1_weighted)

Weighted F1 Score: 0.4984656986514679

In [249]:
# 8. ROC-AUC score
roc_auc = roc_auc_score(
    Y_test,
    grid.predict_proba(X_test_scaled)[:, 1]
)

print("ROC-AUC Score:", roc_auc)

ROC-AUC Score: 0.5147296663485954

In [250]:
# 9. Display hyperparameter tuning results
table = pd.DataFrame(re)
print(table)

    mean_fit_time  std_fit_time  mean_score_time  std_score_time param_metric  \
0        0.014304      0.004082         0.050022        0.007440    euclidean
1        0.012187      0.002095         0.047022        0.006517    euclidean
2        0.014593      0.004352         0.046315        0.002077    euclidean
3        0.012475      0.008588         0.045773        0.005202    euclidean
4        0.008551      0.004320         0.051959        0.008260    euclidean
5        0.017259      0.004820         0.049504        0.003341    euclidean
6        0.012870      0.003573         0.049815        0.005974    euclidean
7        0.016581      0.010216         0.049706        0.003125    euclidean
8        0.011159      0.005938         0.052258        0.004242    euclidean
9        0.009505      0.005479         0.047986        0.006292    euclidean
10       0.013353      0.003059         0.046848        0.005773    euclidean
11       0.014276      0.006305         0.046294        0.004200    euclidean
12       0.015603      0.005394         0.045556        0.003561    euclidean
13       0.013040      0.007428         0.051666        0.006300    euclidean
14       0.012368      0.002881         0.048641        0.004632    euclidean
15       0.010784      0.007461         0.046163        0.007392    euclidean
16       0.010345      0.000391         0.050669        0.006375    manhattan
17       0.010140      0.000041         0.054560        0.004980    manhattan
18       0.012141      0.004027         0.056620        0.004942    manhattan
19       0.010118      0.000037         0.058613        0.009865    manhattan
20       0.014156      0.004946         0.054789        0.005024    manhattan
21       0.012236      0.003976         0.051531        0.000815    manhattan
22       0.010492      0.000644         0.052615        0.004046    manhattan
23       0.010089      0.000009         0.052592        0.003987    manhattan
24       0.012132      0.004020         0.052572        0.004072    manhattan
25       0.012139      0.004042         0.052570        0.004147    manhattan
26       0.016247      0.008231         0.053276        0.002796    manhattan
27       0.012415      0.005074         0.050590        0.000059    manhattan
28       0.010141      0.000093         0.060720        0.006436    manhattan
29       0.012139      0.004052         0.053165        0.004285    manhattan
30       0.010340      0.000441         0.052733        0.003946    manhattan
31       0.010093      0.000017         0.051375        0.000885    manhattan
32       0.013086      0.006692         0.050830        0.000285    minkowski
33       0.010109      0.000026         0.048516        0.004072    minkowski
34       0.012172      0.004149         0.050125        0.004986    minkowski
35       0.010678      0.001056         0.046855        0.005104    minkowski
36       0.010114      0.000018         0.050863        0.000521    minkowski
37       0.010111      0.000018         0.054852        0.004478    minkowski
38       0.012908      0.003802         0.051169        0.008857    minkowski
39       0.010550      0.000624         0.050162        0.000550    minkowski
40       0.010099      0.000014         0.050592        0.000059    minkowski
41       0.010199      0.000133         0.052651        0.004018    minkowski
42       0.010107      0.000041         0.050820        0.000149    minkowski
43       0.012388      0.003938         0.044729        0.004752    minkowski
44       0.010090      0.000017         0.056826        0.005173    minkowski
45       0.012120      0.004043         0.050530        0.000053    minkowski
46       0.012145      0.004026         0.050559        0.000057    minkowski
47       0.010137      0.000036         0.050639        0.000108    minkowski

    param_n_neighbors  param_p param_weights  \
0                   3        1       uniform
1                   3        1      distance
2                   3        2       uniform
3                   3        2      distance
4                   5        1       uniform
5                   5        1      distance
6                   5        2       uniform
7                   5        2      distance
8                   7        1       uniform
9                   7        1      distance
10                  7        2       uniform
11                  7        2      distance
12                  9        1       uniform
13                  9        1      distance
14                  9        2       uniform
15                  9        2      distance
16                  3        1       uniform
17                  3        1      distance
18                  3        2       uniform
19                  3        2      distance
20                  5        1       uniform
21                  5        1      distance
22                  5        2       uniform
23                  5        2      distance
24                  7        1       uniform
25                  7        1      distance
26                  7        2       uniform
27                  7        2      distance
28                  9        1       uniform
29                  9        1      distance
30                  9        2       uniform
31                  9        2      distance
32                  3        1       uniform
33                  3        1      distance
34                  3        2       uniform
35                  3        2      distance
36                  5        1       uniform
37                  5        1      distance
38                  5        2       uniform
39                  5        2      distance
40                  7        1       uniform
41                  7        1      distance
42                  7        2       uniform
43                  7        2      distance
44                  9        1       uniform
45                  9        1      distance
46                  9        2       uniform
47                  9        2      distance

                                               params  split0_test_score  \
0   {'metric': 'euclidean', 'n_neighbors': 3, 'p':...           0.491444
1   {'metric': 'euclidean', 'n_neighbors': 3, 'p':...           0.497271
2   {'metric': 'euclidean', 'n_neighbors': 3, 'p':...           0.491444
3   {'metric': 'euclidean', 'n_neighbors': 3, 'p':...           0.497271
4   {'metric': 'euclidean', 'n_neighbors': 5, 'p':...           0.496923
5   {'metric': 'euclidean', 'n_neighbors': 5, 'p':...           0.500168
6   {'metric': 'euclidean', 'n_neighbors': 5, 'p':...           0.496923
7   {'metric': 'euclidean', 'n_neighbors': 5, 'p':...           0.500168
8   {'metric': 'euclidean', 'n_neighbors': 7, 'p':...           0.495818
9   {'metric': 'euclidean', 'n_neighbors': 7, 'p':...           0.493167
10  {'metric': 'euclidean', 'n_neighbors': 7, 'p':...           0.495818
11  {'metric': 'euclidean', 'n_neighbors': 7, 'p':...           0.493167
12  {'metric': 'euclidean', 'n_neighbors': 9, 'p':...           0.473045
13  {'metric': 'euclidean', 'n_neighbors': 9, 'p':...           0.496502
14  {'metric': 'euclidean', 'n_neighbors': 9, 'p':...           0.473045
15  {'metric': 'euclidean', 'n_neighbors': 9, 'p':...           0.496502
16  {'metric': 'manhattan', 'n_neighbors': 3, 'p':...           0.480056
17  {'metric': 'manhattan', 'n_neighbors': 3, 'p':...           0.493259
18  {'metric': 'manhattan', 'n_neighbors': 3, 'p':...           0.480056
19  {'metric': 'manhattan', 'n_neighbors': 3, 'p':...           0.493259
20  {'metric': 'manhattan', 'n_neighbors': 5, 'p':...           0.495055
21  {'metric': 'manhattan', 'n_neighbors': 5, 'p':...           0.497946
22  {'metric': 'manhattan', 'n_neighbors': 5, 'p':...           0.495055
23  {'metric': 'manhattan', 'n_neighbors': 5, 'p':...           0.497946
24  {'metric': 'manhattan', 'n_neighbors': 7, 'p':...           0.489981
25  {'metric': 'manhattan', 'n_neighbors': 7, 'p':...           0.489501
26  {'metric': 'manhattan', 'n_neighbors': 7, 'p':...           0.489981
27  {'metric': 'manhattan', 'n_neighbors': 7, 'p':...           0.489501
28  {'metric': 'manhattan', 'n_neighbors': 9, 'p':...           0.485080
29  {'metric': 'manhattan', 'n_neighbors': 9, 'p':...           0.491725
30  {'metric': 'manhattan', 'n_neighbors': 9, 'p':...           0.485080
31  {'metric': 'manhattan', 'n_neighbors': 9, 'p':...           0.491725
32  {'metric': 'minkowski', 'n_neighbors': 3, 'p':...           0.480056
33  {'metric': 'minkowski', 'n_neighbors': 3, 'p':...           0.493259
34  {'metric': 'minkowski', 'n_neighbors': 3, 'p':...           0.491444
35  {'metric': 'minkowski', 'n_neighbors': 3, 'p':...           0.497271
36  {'metric': 'minkowski', 'n_neighbors': 5, 'p':...           0.495055
37  {'metric': 'minkowski', 'n_neighbors': 5, 'p':...           0.497946
38  {'metric': 'minkowski', 'n_neighbors': 5, 'p':...           0.496923
39  {'metric': 'minkowski', 'n_neighbors': 5, 'p':...           0.500168
40  {'metric': 'minkowski', 'n_neighbors': 7, 'p':...           0.489981
41  {'metric': 'minkowski', 'n_neighbors': 7, 'p':...           0.489501
42  {'metric': 'minkowski', 'n_neighbors': 7, 'p':...           0.495818
43  {'metric': 'minkowski', 'n_neighbors': 7, 'p':...           0.493167
44  {'metric': 'minkowski', 'n_neighbors': 9, 'p':...           0.485080
45  {'metric': 'minkowski', 'n_neighbors': 9, 'p':...           0.491725
46  {'metric': 'minkowski', 'n_neighbors': 9, 'p':...           0.473045
47  {'metric': 'minkowski', 'n_neighbors': 9, 'p':...           0.496502

    split1_test_score  split2_test_score  split3_test_score  \
0            0.516055           0.523959           0.442315
1            0.509794           0.518250           0.448461
2            0.516055           0.523959           0.442315
3            0.509794           0.518250           0.448461
4            0.496712           0.531204           0.445871
5            0.490038           0.516327           0.452472
6            0.496712           0.531204           0.445871
7            0.490038           0.516327           0.452472
8            0.505810           0.534147           0.452451
9            0.496053           0.513472           0.457324
10           0.505810           0.534147           0.452451
11           0.496053           0.513472           0.457324
12           0.497170           0.536519           0.492211
13           0.494532           0.514900           0.474109
14           0.497170           0.536519           0.492211
15           0.494532           0.514900           0.474109
16           0.514643           0.522391           0.444915
17           0.510918           0.515708           0.447406
18           0.514643           0.522391           0.444915
19           0.510918           0.515708           0.447406
20           0.501501           0.532110           0.446822
21           0.492194           0.519458           0.458412
22           0.501501           0.532110           0.446822
23           0.492194           0.519458           0.458412
24           0.508051           0.533003           0.448805
25           0.498195           0.516909           0.456618
26           0.508051           0.533003           0.448805
27           0.498195           0.516909           0.456618
28           0.506614           0.533504           0.492273
29           0.496671           0.516327           0.473682
30           0.506614           0.533504           0.492273
31           0.496671           0.516327           0.473682
32           0.514643           0.522391           0.444915
33           0.510918           0.515708           0.447406
34           0.516055           0.523959           0.442315
35           0.509794           0.518250           0.448461
36           0.501501           0.532110           0.446822
37           0.492194           0.519458           0.458412
38           0.496712           0.531204           0.445871
39           0.490038           0.516327           0.452472
40           0.508051           0.533003           0.448805
41           0.498195           0.516909           0.456618
42           0.505810           0.534147           0.452451
43           0.496053           0.513472           0.457324
44           0.506614           0.533504           0.492273
45           0.496671           0.516327           0.473682
46           0.497170           0.536519           0.492211
47           0.494532           0.514900           0.474109

    split4_test_score  mean_test_score  std_test_score  rank_test_score
0            0.496773         0.494109        0.028529               13
1            0.487950         0.492345        0.024269               22
2            0.496773         0.494109        0.028529               13
3            0.487950         0.492345        0.024269               22
4            0.486401         0.491422        0.027353               31
5            0.480488         0.487899        0.021322               46
6            0.486401         0.491422        0.027353               31
7            0.480488         0.487899        0.021322               46
8            0.476131         0.492871        0.027546               19
9            0.480994         0.488202        0.018602               43
10           0.476131         0.492871        0.027546               19
11           0.480994         0.488202        0.018602               43
12           0.480256         0.495840        0.022055               10
13           0.504208         0.496850        0.013436                4
14           0.480256         0.495840        0.022055               10
15           0.504208         0.496850        0.013436                4
16           0.496773         0.491756        0.027635               28
17           0.489031         0.491264        0.024151               34
18           0.496773         0.491756        0.027635               28
19           0.489031         0.491264        0.024151               34
20           0.491871         0.493472        0.027345               16
21           0.482359         0.490074        0.019959               37
22           0.491871         0.493472        0.027345               16
23           0.482359         0.490074        0.019959               37
24           0.480173         0.492003        0.028102               25
25           0.487407         0.489726        0.019556               40
26           0.480173         0.492003        0.028102               25
27           0.487407         0.489726        0.019556               40
28           0.484973         0.500489        0.018293                1
29           0.503509         0.496383        0.014040                7
30           0.484973         0.500489        0.018293                1
31           0.503509         0.496383        0.014040                7
32           0.496773         0.491756        0.027635               28
33           0.489031         0.491264        0.024151               34
34           0.496773         0.494109        0.028529               13
35           0.487950         0.492345        0.024269               22
36           0.491871         0.493472        0.027345               16
37           0.482359         0.490074        0.019959               37
38           0.486401         0.491422        0.027353               31
39           0.480488         0.487899        0.021322               46
40           0.480173         0.492003        0.028102               25
41           0.487407         0.489726        0.019556               40
42           0.476131         0.492871        0.027546               19
43           0.480994         0.488202        0.018602               43
44           0.484973         0.500489        0.018293                1
45           0.503509         0.496383        0.014040                7
46           0.480256         0.495840        0.022055               10
47           0.504208         0.496850        0.013436                4

In [251]:
# 10. Display selected SelectKBest features
selected_features = X_train_selected.columns.tolist()

print("\nSelected SelectKBest Features:")
print(selected_features)

print("\nNumber of selected features:", len(selected_features))

Selected SelectKBest Features:
['Age', 'Heart_Rate', 'Follow_Up', 'Cholesterol_Status_normal', 'Age_Group', 'BMI_Category']

Number of selected features: 6

# Decision tree classifier

In [252]:
# 1. Model building
import pandas as pd
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier

param_grid = {
    "criterion": ["gini", "entropy"],
    "max_features": [None, "sqrt", "log2"],
    "splitter": ["best", "random"]
}

grid = GridSearchCV(
    DecisionTreeClassifier(random_state=42),
    param_grid,
    refit=True,
    n_jobs=-1,
    verbose=3,
    scoring="f1_weighted"
)

# Fit using SelectKBest-selected and scaled training features
grid.fit(X_train_scaled, Y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

GridSearchCV(estimator=DecisionTreeClassifier(random_state=42), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': [None, 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             scoring='f1_weighted', verbose=3)

# Model evaluation

In [253]:
# 2. Test on test data using evaluation metrics
re = grid.cv_results_

grid_predictions = grid.predict(X_test_scaled)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, grid_predictions)

from sklearn.metrics import classification_report
clf_report = classification_report(
    Y_test, grid_predictions, zero_division=0
)

In [254]:
# 3. Weighted F1 score
from sklearn.metrics import f1_score

f1_weighted = f1_score(
    Y_test, grid_predictions, average="weighted"
)

print(
    "Weighted F1 score for best parameters:",
    grid.best_params_,
    f1_weighted
)

Weighted F1 score for best parameters: {'criterion': 'gini', 'max_features': 'sqrt', 'splitter': 'best'} 0.4562129404372088

In [255]:
# 4. Confusion matrix
print("The Confusion Matrix:\n", cm)

The Confusion Matrix:
 [[365 119]
 [387 124]]

In [256]:
# 5. Classification report
print("The Report:\n", clf_report)

The Report:
               precision    recall  f1-score   support

           0       0.49      0.75      0.59       484
           1       0.51      0.24      0.33       511

    accuracy                           0.49       995
   macro avg       0.50      0.50      0.46       995
weighted avg       0.50      0.49      0.46       995

In [257]:
# 6. ROC-AUC score
from sklearn.metrics import roc_auc_score

roc_auc = roc_auc_score(
    Y_test,
    grid.predict_proba(X_test_scaled)[:, 1]
)

print("ROC-AUC Score:", roc_auc)

ROC-AUC Score: 0.5214475748410992

In [258]:
# 7. Display hyperparameter tuning results
table = pd.DataFrame(grid.cv_results_)
print(table)

    mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.019005      0.004777         0.012779        0.002771
1        0.009032      0.006703         0.014718        0.004004
2        0.009503      0.005230         0.016912        0.005607
3        0.005178      0.004842         0.013754        0.006171
4        0.007996      0.003741         0.014209        0.004904
5        0.008096      0.004048         0.012180        0.004184
6        0.012129      0.004044         0.012268        0.004285
7        0.006079      0.004964         0.018307        0.007765
8        0.010238      0.000190         0.016279        0.005061
9        0.010125      0.006400         0.014148        0.004947
10       0.010077      0.000035         0.012348        0.003963
11       0.008491      0.003735         0.012333        0.003971

   param_criterion param_max_features param_splitter  \
0             gini               None           best
1             gini               None         random
2             gini               sqrt           best
3             gini               sqrt         random
4             gini               log2           best
5             gini               log2         random
6          entropy               None           best
7          entropy               None         random
8          entropy               sqrt           best
9          entropy               sqrt         random
10         entropy               log2           best
11         entropy               log2         random

                                               params  split0_test_score  \
0   {'criterion': 'gini', 'max_features': None, 's...           0.512119
1   {'criterion': 'gini', 'max_features': None, 's...           0.494361
2   {'criterion': 'gini', 'max_features': 'sqrt', ...           0.501380
3   {'criterion': 'gini', 'max_features': 'sqrt', ...           0.491007
4   {'criterion': 'gini', 'max_features': 'log2', ...           0.501380
5   {'criterion': 'gini', 'max_features': 'log2', ...           0.491007
6   {'criterion': 'entropy', 'max_features': None,...           0.502666
7   {'criterion': 'entropy', 'max_features': None,...           0.502034
8   {'criterion': 'entropy', 'max_features': 'sqrt...           0.498040
9   {'criterion': 'entropy', 'max_features': 'sqrt...           0.491686
10  {'criterion': 'entropy', 'max_features': 'log2...           0.498040
11  {'criterion': 'entropy', 'max_features': 'log2...           0.491686

    split1_test_score  split2_test_score  split3_test_score  \
0            0.464929           0.452534           0.466251
1            0.468800           0.467631           0.471289
2            0.479076           0.470600           0.478412
3            0.467414           0.464971           0.475608
4            0.479076           0.470600           0.478412
5            0.467414           0.464971           0.475608
6            0.467631           0.456822           0.468842
7            0.470333           0.460079           0.476009
8            0.470333           0.465685           0.473682
9            0.467414           0.464971           0.472961
10           0.470333           0.465685           0.473682
11           0.467414           0.464971           0.472961

    split4_test_score  mean_test_score  std_test_score  rank_test_score
0            0.485780         0.476322        0.020823                5
1            0.470971         0.474610        0.009969               12
2            0.473085         0.480511        0.010912                1
3            0.480424         0.475885        0.009383                6
4            0.473085         0.480511        0.010912                1
5            0.480424         0.475885        0.009383                6
6            0.487459         0.476684        0.016304                4
7            0.479027         0.477497        0.013866                3
8            0.467033         0.474955        0.011871                8
9            0.476117         0.474630        0.009394               10
10           0.467033         0.474955        0.011871                8
11           0.476117         0.474630        0.009394               10

In [259]:
# 8. Display selected SelectKBest features
print("\nSelected Features:")
print(X_train_selected.columns.tolist())

Selected Features:
['Age', 'Heart_Rate', 'Follow_Up', 'Cholesterol_Status_normal', 'Age_Group', 'BMI_Category']

# Logistic regression

In [260]:

# 1. Model building with hyperparameter tuning
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV

param_grid = {
    "solver": ["newton-cg", "lbfgs", "liblinear", "saga"],
    "penalty": ["l2"]
}

grid = GridSearchCV(
    LogisticRegression(max_iter=5000, random_state=42),
    param_grid,
    refit=True,
    verbose=3,
    n_jobs=-1,
    scoring="f1_weighted"
)

# Fit the model using selected and scaled training data
grid.fit(X_train_scaled, Y_train)

Fitting 5 folds for each of 4 candidates, totalling 20 fits

GridSearchCV(estimator=LogisticRegression(max_iter=5000, random_state=42),
             n_jobs=-1,
             param_grid={'penalty': ['l2'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'saga']},
             scoring='f1_weighted', verbose=3)

# Model evaluation

In [261]:
# 2. Predict using test data
re = grid.cv_results_
grid_predictions = grid.predict(X_test_scaled)

In [262]:
# 3. Confusion matrix
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(Y_test, grid_predictions)

In [263]:

# 4. Classification report
from sklearn.metrics import classification_report

clf_report = classification_report(
    Y_test, grid_predictions, zero_division=0
)

In [264]:
# 5. Print best parameters
print("Best Parameters:", grid.best_params_)

Best Parameters: {'penalty': 'l2', 'solver': 'newton-cg'}

In [265]:
print("the clf report\n", clf_report)

the clf report
               precision    recall  f1-score   support

           0       0.48      0.61      0.53       484
           1       0.49      0.36      0.42       511

    accuracy                           0.48       995
   macro avg       0.48      0.49      0.48       995
weighted avg       0.49      0.48      0.47       995

In [266]:
# 6. Weighted F1 score
from sklearn.metrics import f1_score

f1_weighted = f1_score(
    Y_test, grid_predictions, average="weighted"
)

print("Weighted F1 Score:", f1_weighted)

Weighted F1 Score: 0.4741686171601819

In [267]:
# 7. Print confusion matrix
print("The Confusion Matrix:\n", cm)

The Confusion Matrix:
 [[296 188]
 [327 184]]

In [268]:
# 8. Print classification report
print("The Classification Report:\n", clf_report)

The Classification Report:
               precision    recall  f1-score   support

           0       0.48      0.61      0.53       484
           1       0.49      0.36      0.42       511

    accuracy                           0.48       995
   macro avg       0.48      0.49      0.48       995
weighted avg       0.49      0.48      0.47       995

In [269]:
# 9. ROC-AUC score
from sklearn.metrics import roc_auc_score

roc_auc = roc_auc_score(
    Y_test, grid.predict_proba(X_test_scaled)[:, 1]
)

print("ROC-AUC Score:", roc_auc)

ROC-AUC Score: 0.4871686532645436

In [270]:
# 10. Display hyperparameter tuning results
table = pd.DataFrame.from_dict(re)
print(table)

   mean_fit_time  std_fit_time  mean_score_time  std_score_time param_penalty  \
0       0.015965      0.008066         0.016591        0.002368            l2
1       0.019967      0.011956         0.014660        0.004438            l2
2       0.007638      0.003331         0.011797        0.004088            l2
3       0.022604      0.004298         0.010184        0.000048            l2

  param_solver                                    params  split0_test_score  \
0    newton-cg  {'penalty': 'l2', 'solver': 'newton-cg'}           0.500306
1        lbfgs      {'penalty': 'l2', 'solver': 'lbfgs'}           0.500306
2    liblinear  {'penalty': 'l2', 'solver': 'liblinear'}           0.500306
3         saga       {'penalty': 'l2', 'solver': 'saga'}           0.500306

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.491734           0.467454           0.474202           0.474694
1           0.491734           0.467454           0.474202           0.474694
2           0.491734           0.467454           0.473087           0.474694
3           0.491734           0.467454           0.473087           0.474694

   mean_test_score  std_test_score  rank_test_score
0         0.481678        0.012289                1
1         0.481678        0.012289                1
2         0.481455        0.012432                3
3         0.481455        0.012432                3

In [271]:
# 11. Display selected features
print("\nSelected SelectKBest Features:")
print(X_train_selected.columns.tolist())

Selected SelectKBest Features:
['Age', 'Heart_Rate', 'Follow_Up', 'Cholesterol_Status_normal', 'Age_Group', 'BMI_Category']

# Naive bayes

In [272]:
# 1. Model building with hyperparameter tuning
import pandas as pd
from sklearn.model_selection import GridSearchCV
from sklearn.naive_bayes import GaussianNB

param_grid = {
    "var_smoothing": [1e-9, 1e-8, 1e-7]
}

grid = GridSearchCV(
    GaussianNB(),
    param_grid,
    scoring="f1_weighted",
    n_jobs=-1,
    verbose=3,
    refit=True
)

# Fit using selected and scaled training data
grid.fit(X_train_scaled, Y_train)

Fitting 5 folds for each of 3 candidates, totalling 15 fits

GridSearchCV(estimator=GaussianNB(), n_jobs=-1,
             param_grid={'var_smoothing': [1e-09, 1e-08, 1e-07]},
             scoring='f1_weighted', verbose=3)

In [273]:
# 2. Get hyperparameter tuning results
re = grid.cv_results_

# Predict using test data
grid_prediction = grid.predict(X_test_scaled)

# Model evaluation

In [274]:
# 3. Confusion matrix
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(Y_test, grid_prediction)

In [275]:
# 4. Classification report
from sklearn.metrics import classification_report

cl_report = classification_report(
    Y_test, grid_prediction, zero_division=0
)

In [276]:
# 5. Print best parameters
print("Best Parameters:", grid.best_params_)

Best Parameters: {'var_smoothing': 1e-09}

In [277]:
# 6. Weighted F1 score
from sklearn.metrics import f1_score

f1_weighted = f1_score(
    Y_test, grid_prediction, average="weighted"
)

print("Weighted F1 Score:", f1_weighted)

Weighted F1 Score: 0.4810470754559964

In [278]:
# 7. Print confusion matrix
print("The Confusion Matrix:\n", cm)

The Confusion Matrix:
 [[281 203]
 [309 202]]

In [279]:
# 8. Print classification report
print("The Classification Report:\n", cl_report)

The Classification Report:
               precision    recall  f1-score   support

           0       0.48      0.58      0.52       484
           1       0.50      0.40      0.44       511

    accuracy                           0.49       995
   macro avg       0.49      0.49      0.48       995
weighted avg       0.49      0.49      0.48       995

In [280]:
# 9. ROC-AUC score
from sklearn.metrics import roc_auc_score

roc_auc = roc_auc_score(
    Y_test, grid.predict_proba(X_test_scaled)[:, 1]
)

print("ROC-AUC Score:", roc_auc)

ROC-AUC Score: 0.4862710452685546

In [281]:
# 10. Display hyperparameter tuning results
table = pd.DataFrame.from_dict(re)
print(table)

   mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0       0.008022      0.004101         0.017533        0.002723
1       0.003357      0.002094         0.014016        0.003697
2       0.006082      0.004966         0.010654        0.000648

   param_var_smoothing                    params  split0_test_score  \
0         1.000000e-09  {'var_smoothing': 1e-09}           0.513327
1         1.000000e-08  {'var_smoothing': 1e-08}           0.513327
2         1.000000e-07  {'var_smoothing': 1e-07}           0.513327

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.500598             0.4755           0.494621           0.480994
1           0.500598             0.4755           0.494621           0.480994
2           0.500598             0.4755           0.494621           0.480994

   mean_test_score  std_test_score  rank_test_score
0         0.493008        0.013594                1
1         0.493008        0.013594                1
2         0.493008        0.013594                1

In [282]:
# 11. Display selected features
print("\nSelected SelectKBest Features:")
print(X_train_selected.columns.tolist())

Selected SelectKBest Features:
['Age', 'Heart_Rate', 'Follow_Up', 'Cholesterol_Status_normal', 'Age_Group', 'BMI_Category']

# Random forest

In [329]:
# 1. Model building with hyperparameter tuning
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

param_grid = {
    "criterion": ["gini", "entropy"],
    "max_features": ["log2", "sqrt", None],
    "n_estimators": [10, 50, 100]
}

grid = GridSearchCV(
    RandomForestClassifier(random_state=42),
    param_grid,
    refit=True,
    verbose=3,
    n_jobs=-1,
    scoring="f1_weighted"
)

# Fit using selected training features
grid.fit(X_train_scaled, Y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

GridSearchCV(estimator=RandomForestClassifier(random_state=42), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['log2', 'sqrt', None],
                         'n_estimators': [10, 50, 100]},
             scoring='f1_weighted', verbose=3)

In [330]:
# 2. Get hyperparameter tuning results
re = grid.cv_results_

# Predict using test data
grid_predictions = grid.predict(X_test_scaled)

# Evaluation matric

In [331]:
# 3. Confusion matrix
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(Y_test, grid_predictions)

In [332]:
# 4. Classification report
from sklearn.metrics import classification_report

clf_report = classification_report(
    Y_test, grid_predictions, zero_division=0
)

In [333]:
# 5. Print best parameters
print("Best Parameters:", grid.best_params_)

Best Parameters: {'criterion': 'gini', 'max_features': None, 'n_estimators': 10}

In [334]:
# 6. Display hyperparameter tuning results
table = pd.DataFrame.from_dict(re)
print(table)

    mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.064750      0.003989         0.016698        0.001716
1        0.324281      0.024928         0.021450        0.004047
2        0.635255      0.028694         0.038166        0.002865
3        0.071127      0.006480         0.013932        0.005112
4        0.296250      0.013399         0.027610        0.002056
5        0.577574      0.011166         0.043129        0.007827
6        0.086755      0.004491         0.019118        0.005534
7        0.434794      0.005401         0.028001        0.002767
8        0.880270      0.017517         0.036523        0.005747
9        0.064705      0.005325         0.010314        0.008571
10       0.319126      0.015581         0.024728        0.002572
11       0.654338      0.020196         0.036058        0.006369
12       0.062251      0.005429         0.019981        0.004763
13       0.311370      0.008085         0.034690        0.009873
14       0.625004      0.012402         0.040236        0.004746
15       0.101747      0.006664         0.013475        0.002826
16       0.483648      0.015158         0.023128        0.008924
17       0.894923      0.109361         0.029047        0.006622

   param_criterion param_max_features  param_n_estimators  \
0             gini               log2                  10
1             gini               log2                  50
2             gini               log2                 100
3             gini               sqrt                  10
4             gini               sqrt                  50
5             gini               sqrt                 100
6             gini               None                  10
7             gini               None                  50
8             gini               None                 100
9          entropy               log2                  10
10         entropy               log2                  50
11         entropy               log2                 100
12         entropy               sqrt                  10
13         entropy               sqrt                  50
14         entropy               sqrt                 100
15         entropy               None                  10
16         entropy               None                  50
17         entropy               None                 100

                                               params  split0_test_score  \
0   {'criterion': 'gini', 'max_features': 'log2', ...           0.490672
1   {'criterion': 'gini', 'max_features': 'log2', ...           0.493143
2   {'criterion': 'gini', 'max_features': 'log2', ...           0.493143
3   {'criterion': 'gini', 'max_features': 'sqrt', ...           0.490672
4   {'criterion': 'gini', 'max_features': 'sqrt', ...           0.493143
5   {'criterion': 'gini', 'max_features': 'sqrt', ...           0.493143
6   {'criterion': 'gini', 'max_features': None, 'n...           0.488318
7   {'criterion': 'gini', 'max_features': None, 'n...           0.497218
8   {'criterion': 'gini', 'max_features': None, 'n...           0.501909
9   {'criterion': 'entropy', 'max_features': 'log2...           0.486553
10  {'criterion': 'entropy', 'max_features': 'log2...           0.497831
11  {'criterion': 'entropy', 'max_features': 'log2...           0.495181
12  {'criterion': 'entropy', 'max_features': 'sqrt...           0.486553
13  {'criterion': 'entropy', 'max_features': 'sqrt...           0.497831
14  {'criterion': 'entropy', 'max_features': 'sqrt...           0.495181
15  {'criterion': 'entropy', 'max_features': None,...           0.490755
16  {'criterion': 'entropy', 'max_features': None,...           0.492294
17  {'criterion': 'entropy', 'max_features': None,...           0.496978

    split1_test_score  split2_test_score  split3_test_score  \
0            0.519876           0.486447           0.484580
1            0.493069           0.487179           0.486044
2            0.496136           0.487595           0.483909
3            0.519876           0.486447           0.484580
4            0.493069           0.487179           0.486044
5            0.496136           0.487595           0.483909
6            0.518515           0.490462           0.479790
7            0.485442           0.488108           0.476131
8            0.486980           0.488383           0.482483
9            0.521462           0.480110           0.484928
10           0.489396           0.486157           0.493008
11           0.500396           0.485556           0.487581
12           0.521462           0.480110           0.484928
13           0.489396           0.486157           0.493008
14           0.500396           0.485556           0.487581
15           0.508598           0.495784           0.481645
16           0.487746           0.490121           0.477221
17           0.493302           0.493440           0.481360

    split4_test_score  mean_test_score  std_test_score  rank_test_score
0            0.490418         0.494399        0.012949                2
1            0.487239         0.489335        0.003108               14
2            0.493924         0.490941        0.004503                9
3            0.490418         0.494399        0.012949                2
4            0.487239         0.489335        0.003108               14
5            0.493924         0.490941        0.004503                9
6            0.502444         0.495906        0.013423                1
7            0.490901         0.487560        0.006926               18
8            0.483381         0.488627        0.006992               16
9            0.497755         0.494161        0.014824                4
10           0.480301         0.489339        0.005956               12
11           0.487044         0.491152        0.005703                7
12           0.497755         0.494161        0.014824                4
13           0.480301         0.489339        0.005956               12
14           0.487044         0.491152        0.005703                7
15           0.490315         0.493419        0.008847                6
16           0.490901         0.487657        0.005422               17
17           0.484989         0.490014        0.005851               11

In [335]:
# 7. Weighted F1 score
from sklearn.metrics import f1_score

f1_weighted = f1_score(
    Y_test, grid_predictions, average="weighted"
)

print("Weighted F1 Score:", f1_weighted)

Weighted F1 Score: 0.4976104198120648

In [336]:
# 8. ROC-AUC score
from sklearn.metrics import roc_auc_score

roc_auc = roc_auc_score(
    Y_test, grid.predict_proba(X_test_scaled)[:, 1]
)

print("ROC-AUC Score:", roc_auc)

ROC-AUC Score: 0.5122187899273827

In [337]:
# 9. Print confusion matrix
print("The Confusion Matrix:\n", cm)

The Confusion Matrix:
 [[312 172]
 [319 192]]

In [338]:
# 10. Print classification report
print("The Classification Report:\n", clf_report)

The Classification Report:
               precision    recall  f1-score   support

           0       0.49      0.64      0.56       484
           1       0.53      0.38      0.44       511

    accuracy                           0.51       995
   macro avg       0.51      0.51      0.50       995
weighted avg       0.51      0.51      0.50       995

In [339]:
# 11. Display test features
print("\nX_test:")
print(X_test_scaled)

X_test:
[[ 0.01197202  3.30441996  1.78103569  0.4778052   0.09460007  3.38455892]
 [-3.27314916  0.01883601  1.78103569 -2.09290314 -3.19037701 -0.22176729]
 [ 0.01197202  0.01883601 -0.56147106  0.4778052   0.09460007 -0.22176729]
 ...
 [ 0.01197202  0.01883601 -0.56147106  0.4778052   0.09460007 -0.22176729]
 [ 0.01197202  0.01883601 -0.56147106  0.4778052   0.09460007 -0.22176729]
 [ 0.01197202  0.01883601 -0.56147106  0.4778052   0.09460007 -0.22176729]]

In [340]:
# 12. Create an empty results DataFrame
table_pr = pd.DataFrame()

In [341]:
# Display selected features
print("\nSelected SelectKBest Features:")
print(X_train_selected.columns.tolist())

Selected SelectKBest Features:
['Age', 'Heart_Rate', 'Follow_Up', 'Cholesterol_Status_normal', 'Age_Group', 'BMI_Category']

In [350]:
import pickle

with open("RandomForest_model.pkl", "wb") as file:
    pickle.dump(grid.best_estimator_, file)


print("Random Forest model saved successfully.")

Random Forest model saved successfully.

# SVM

In [296]:

# 1. Model building with hyperparameter tuning
#import pandas as pd
#from sklearn.model_selection import GridSearchCV
#from sklearn.svm import SVC

#param_grid = {
    #"kernel": ["linear", "rbf", "poly", "sigmoid"],
    #"gamma": ["auto", "scale"],
    #"C": [10, 100, 1000, 2000, 3000]
#}

#grid = GridSearchCV(
    #SVC(probability=True, random_state=42),
    #param_grid,
    #refit=True,
    #verbose=3,
    #n_jobs=-1,
    #scoring="f1_weighted"
#)

# Fit using selected and scaled training data
#grid.fit(X_train_scaled, Y_train)

In [297]:
# 2. Get hyperparameter tuning results
#re = grid.cv_results_

# Predict using test data
#grid_predictions = grid.predict(X_test_scaled)

# Model evaluation

In [298]:
# 3. Confusion matrix
#from sklearn.metrics import confusion_matrix

#cm = confusion_matrix(Y_test, grid_predictions)

In [299]:
# 4. Classification report
#from sklearn.metrics import classification_report

#clf_report = classification_report(
    #Y_test, grid_predictions, zero_division=0
#)

In [300]:
# 5. Print best parameters
#print("Best Parameters:", grid.best_params_)

In [301]:
# 6. Print classification report
#print("The Classification Report:\n", clf_report)

In [302]:
# 7. Weighted F1 score
#from sklearn.metrics import f1_score

#f1_weighted = f1_score(
    #Y_test, grid_predictions, average="weighted"
#)

#print("Weighted F1 Score:", f1_weighted)

In [303]:
# 8. Print confusion matrix
#print("The Confusion Matrix:\n", cm)

In [304]:
# 9. ROC-AUC score
#from sklearn.metrics import roc_auc_score

#roc_auc = roc_auc_score(
    #Y_test, grid.predict_proba(X_test_scaled)[:, 1]
#)

#print("ROC-AUC Score:", roc_auc)

In [305]:
# 10. Display hyperparameter tuning results
#table = pd.DataFrame.from_dict(re)
#print(table)

In [306]:
# 11. Display selected features
#print("\nSelected SelectKBest Features:")
#print(X_train_selected.columns.tolist())

# Deployment

In [351]:
import pickle

file_name = "finalized_model_RandomForestClassifier.sav"

In [352]:
# Save the trained classifier (use your classifier's variable name, e.g. classifier / rf_model)
with open(file_name, "wb") as file:
    pickle.dump(classifier, file)

In [353]:
preinput = scaler_kbest.transform([[50, 120, 30, 1, 2, 1]])

In [354]:
preinput

array([[ 0.01197202,  3.30441996,  1.78103569,  0.4778052 ,  0.09460007,
        -0.22176729]])

In [355]:
loaded_model = pickle.load(open("finalized_model_RandomForestClassifier.sav", 'rb'))
result = loaded_model.predict(preinput)

In [356]:
result

array([1])

In [ ]:
#Selected SelectKBest Features:
#['Age', 'Heart_Rate', 'Follow_Up', 'Cholesterol_Status_normal', 'Age_Group', 'BMI_Category']